# Name
name: KBOT-CICD

# Trigger
on: push

env:
  TARGETARCH: amd64

# job
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

#        #Build&Push
 #     - name: Login to GITHUB
  #      uses: docker/login-action@v2
   #     with:
    #     registry: ghcr.io
    #     username: ${{ vars.KBOT_USERNAME }}
     #    password: ${{ secrets.KBOT_REGISTRY_TOKEN  }}
#
 #     - name: Build image
 #       run: make image
  #    - name: Push image
   #     run: make push  




      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
                ghcr.io/${{ github.repository }}:latest
        

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push